version: "3.7"
services:
  node:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src 
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: mysql:8.0.23
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
