version: "3.7"
services:
  node:
    build: ./back-end
    ports:
      - "3000:3000"
    volumes:
      - ./back-end/src:/app/src 
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mysql:8.0.23
    env_file:
      - ./.env
    ports:
      - "3306:3306"
  frontend:
    build: ./front-end
    ports:
      - "3001:3000"
    volumes:
      - ./front-end:/app