const OK = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const CONFLICT = 409;
const FORBIDDEN = 403;

module.exports = {
  OK,
  CREATED,
  NOT_FOUND,
  UNAUTHORIZED,
  FORBIDDEN,
  BAD_REQUEST,
  INTERNAL_SERVER_ERROR,
  CONFLICT,
};
